### ISSUE TITLE
Volta and monorepos

### ISSUE THREAD

**Issue by eridem** [volta-cli/volta#1100] opened 2021-12-06 10:26 UTC
Hi, we are working in several mono-repositories. Here an example of our structure:

```plain
MONOREPO X
~/monorepo-x/.volta/hooks.json
~/monorepo-x/services/a
~/monorepo-x/services/b

MONOREPO Y
~/monorepo-y/.volta/hooks.json
~/monorepo-y/services/c
~/monorepo-y/services/d
```

## Problem

The problem we see is that when we are in `~/monorepo-x/services/a` it will try to fetch the current service `.volta/hooks.json` otherwise, it will jump directly to the `$HOME` one.

We could add the `.volta/hooks.json` per service, but we have hundreds of them per monorepo and this file will be repeated and unnecessary. If we repeat this per each monorepo we have, it will be thousands of duplication.

In another hand, each monorepo has different repositories, so we cannot use the `$HOME` one.

## Desired behavior

Our desired behavior is: if you cannot find `.volta/hooks.json` on the current directory, go a step back on directories until you find it.

This will support having global `hooks.json` per monorepo without duplicating the configuration per service. E.g.

```plain
~/monorepo-x/services/a/.volta/hooks.json   ? ⨯
~/monorepo-x/services/.volta/hooks.json     ? ⨯
~/monorepo-x/.volta/hooks.json              ? ✓

~/monorepo-y/services/c/.volta/hooks.json   ? ⨯
~/monorepo-y/services/.volta/hooks.json     ? ⨯
~/monorepo-y/.volta/hooks.json              ? ✓

~/other-path/.volta/hooks.json  ? ⨯
~/.volta/hooks.json             ? ✓
```

Is there any way now to have this behavior?
Is it something that will be implemented in the future?

**Comment by chriskrycho** [comment] 2021-12-11 17:46
The way we have this designed at present is that you can `extends` a parent `volta` config in your `package.json`, which will correctly use the hooks from the root. So, e.g. in `monorepo-x/services/a/package.json`, and assuming a `monorepo-x/package.json`:


```json
{
  "volta": {
    "extends": "../../package.json"
  }
}
```

For the sake of speed we have consciously chosen *not* to walk the file system like this: it can take a semi-arbitrary amount of time, depending on your folder structure. It's also not a given that it's a desired behavior for all situations like this! See some prior discussions in volta-cli/rfcs#43, #862, #282, and #950.

That doesn't make it a *never*, just a *needs quite a bit of thought and design work*, especially given we don't want to break any existing behavior!

**Comment by eridem** [comment] 2021-12-14 09:41
Thanks @chriskrycho.
Although we still need to add volta section, it is a viable approach for us to go ahead with our monorepos.

**Comment by chriskrycho** [comment] 2021-12-14 15:49
Very good – closing this accordingly as a duplicate of the other issues. Thanks!

**Closed by chriskrycho** 2021-12-14 15:49 UTC
Labels: enhancement
