### ISSUE TITLE
Support for scoop on Windows

### ISSUE THREAD

**Issue by MikeVensel** [volta-cli/volta#743] opened 2020-05-23 15:33 UTC
Would you consider adding support for installing Volta via scoop on Windows?

**Comment by charlespierce** [comment] 2020-05-25 17:35
@MikeVensel Definitely! If I'm reading the docs correctly, we'll need to make a manifest file publicly available so people can install it directly. We can publish on GitHub, or, to make things even simpler, we may be able to use `get.volta.sh/scoop` (we'll have to look at the netlify redirect settings).

**Comment by chawyehsu** [comment] 2020-07-28 08:39
I've implemented this in my scoop bucket, you can install volta via scoop with the following steps:

```sh
# subscribe my bucket
scoop bucket add dorado https://github.com/chawyehsu/dorado
# do installation
scoop install dorado/volta
```

The manifest is located in [here](https://github.com/chawyehsu/dorado/blob/9b57ba90e8feae063729125f8854460a243fd72f/bucket/volta.json) and you can investigate if you want to know the detail.

**Comment by athrunsun** [comment] 2021-01-19 15:23
@chawyehsu I'm sorry but I don't quite understand the [installer script](https://github.com/chawyehsu/dorado/blob/91676f9c3040b5ab19651d79b8d2e0a2598a5c8a/bucket/volta.json#L8) in the app manifest, are you copying `volta-shim.exe` to be `node.exe`/`npm.exe`/`npx.exe`/`yarn.exe`?

If I understand it correctly, you're actually trying to do the following:

```powershell
UpdateExeFile 'node.exe' 'node.exe'
UpdateExeFile 'npm.exe' 'npm.exe'
UpdateExeFile 'npx.exe' 'npx.exe'
UpdateExeFile 'yarn.exe' 'yarn.exe'
```

Please point out if I miss anything...

**Comment by chawyehsu** [comment] 2021-01-19 15:48
@athrunsun 

> are you copying `volta-shim.exe` to be `node.exe`/`npm.exe`/`npx.exe`/`yarn.exe`?
> 
> If I understand it correctly, you're actually trying to do the following:
> 
> ```powershell
> UpdateExeFile 'node.exe' 'node.exe'
> UpdateExeFile 'npm.exe' 'npm.exe'
> UpdateExeFile 'npx.exe' 'npx.exe'
> UpdateExeFile 'yarn.exe' 'yarn.exe'
> ```
> 
> Please point out if I miss anything...

You're right, it does make `volta-shim.exe` copies to be node/npm/npx/yarn. This is a simulation (or reproduction) of what the volta installer does. The volta installer creates shims of those four executables with `volta-shim.exe` while the installation. You could read the detail [here](https://docs.volta.sh/advanced/installers#windows-installer).

**Comment by davidbludlow** [comment] 2022-04-13 00:42
An update: When I tried to use scoop to install volta, today, the resulting volta command would always do nothing, every time it was run.

**Comment by davidbludlow** [comment] 2022-04-26 18:24
I was wrong. The reason that that didn't work for me was because I didn't have Developer Mode for Windows enabled, so the simlinks couldn't be created.

**Comment by chriskrycho** [comment] 2023-12-20 00:37
Looks like this has been resolved. Marking it as closed accordingly!

**Closed by chriskrycho** 2023-12-20 00:37 UTC
