### ISSUE TITLE
Problems with query versions

### ISSUE THREAD

**Issue by tonycody** [volta-cli/volta#1572] opened 2023-11-13 05:20 UTC
How do I know what types of toolchain installations are supported by volta?

Just like sdkman can look up the current toolchain types supported by sdkman via sdk list.

And how do I support e.g. what versions of node are available for me to choose from?

Sdkman supports sdk list java to query which versions of Java can be installed.

**Comment by chriskrycho** [comment] 2023-11-27 16:42
I'm going to close this as a duplicate of #1578. Thanks!

**Closed by chriskrycho** 2023-11-27 16:42 UTC
