### ISSUE TITLE
Failure to unpack

### ISSUE THREAD

**Issue by broksonic21** [volta-cli/volta#1551] opened 2023-09-19 17:41 UTC
We had a ton of machines fail today with failure to unpack node 18.18.0 after upgrading due to nodejs CDN flakiness

Any chance Volta could add support for a --retry for install with a number of times to retry? Would simplify docker and other usages a lot - we saw a lot of CI failures unfortunately. Happens every day, even on older nodes. We cache installs heavily, but any time the cache is busted in our docker layer, we see failures.

**Comment by broksonic21** [comment] 2023-09-19 17:43
```


> npm install

Volta error: Could not unpack Node v18.18.0

Please ensure the correct version is specified.
Error details written to /home/REDACTED/.volta/log/volta-error-REDACTED.log

```

**Comment by broksonic21** [comment] 2023-09-19 18:13
another error:

```
Run npm install --audit false
Volta error: Could not download node@18.18.0
from https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.gz

Please verify your internet connection and ensure the correct version is specified.
Volta error: Error cause: Io Error: Resource temporarily unavailable (os error 11)

Error cause: Io Error: Resource temporarily unavailable (os error 11)
Error: Process completed with exit code 126
```

**Comment by lisonge** [comment] 2023-09-22 12:39
This error is very frequent

https://github.com/gkd-kit/subscription/actions/runs/6274100781/job/17038860167

**Comment by chriskrycho** [comment] 2023-09-23 02:17
> Any chance Volta could add support for a --retry for install with a number of times to retry?

This is a great idea. I'll chat with other folks about it in the Discord, but I think it is both a reasonable way of handling it and also a fairly small piece of implementation. The main things that we would need to consider, off the top of my head, are some kind of exponential back-off and probably some kind of hard limit on number of retries. We don't want Volta to accidentally DDOS servers which may already be having a bad time!

**Comment by chriskrycho** [comment] 2023-09-23 02:38
I believe this is also a duplicate of #1523, so I am closing it as a duplicate. See discussion there for what we *think* may be going on!

**Closed by chriskrycho** 2023-09-23 02:38 UTC
