### ISSUE TITLE
trouble using global executables like vue-cli with volta on windows 10 / wsl2

### ISSUE THREAD

**Issue by 3nigm4** [volta-cli/volta#789] opened 2020-07-28 11:52 UTC
I got trouble with global executable installs (now definitely on WSL 2).

I can install vue-cli, but some commands are not working. `vue create` works fine, but `vue ui` gives me trouble:

vue ui --dev
🚀 Starting GUI...
ERROR Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:

/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
Error: Cannot find module '@vue/cli/lib/util/rcPath'
Require stack:
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/db.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/context.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/plugins.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/connectors/configurations.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/schema/configuration.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/type-defs.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/graphql-server.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/server.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/lib/ui.js
/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/bin/vue.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (/home/bruno/.volta/tools/image/packages/@vue/cli/4.4.6/node_modules/@vue/cli-ui/apollo-server/util/rcFolder.js:4:23)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Module.require (internal/modules/cjs/loader.js:1025:19)

**Comment by ltomes** [comment] 2020-07-28 22:31
To reproduce:
`volta install @vue/cli`
> success: installed @vue/cli@4.4.6 with executables: vue
`vue serve`
>   Command vue serve requires a global addon to be installed.
>   Please run npm install -g @vue/cli-service-global and try again.

If you do that
`npm install -g @vue/cli-service-global`
>Volta error: Global package installs are not supported.
>Use `volta install @vue/cli-service-global` to add a package to your toolchain (see `volta help install` for more info).

`volta install @vue/cli-service-global`
> error: Package has no executables to install.

**Comment by charlespierce** [comment] 2020-07-28 22:43
@3nigm4 Yeah, this is an issue with the file structure of how we keep the global packages, currently tracked in #762 

@ltomes That's a related issue (though you'd likely run into the same problem as well), tracked in #555 

More generally, there are several issues with our current handling of global installs that break in weird ways. I have an RFC open for an approach to rethinking the entire process to better align with how `npm i -g` or `yarn global add` work, you can view and comment on it here: https://github.com/volta-cli/rfcs/pull/45

`npm` Global installs fail because of path issues, however in my experience, Yarn ones continue to work. So if you don't want to use `nvm`, you can work around it currently by doing `VOLTA_UNSAFE_GLOBAL=1 yarn global add` to install vue-cli and the associated global addons. You lose some of the added benefits of Volta globals, but until we can rethink them in a way that handles all of these problems, that may be the cleanest approach.

Closing this in favor of the linked issues.

**Closed by charlespierce** 2020-07-28 22:43 UTC

**Comment by ltomes** [comment] 2020-07-28 23:10
Interesting! I will look into doing global installs with yarn in the short term and see if that behaves as expected.

As an aside; I love what you guys are doing with the toolchain, and understand it's a long road to the ideal solution, and one that works with what npm expects. I'm happy to switch between tools until all these features are complete, you've come a long way from early Notion  builds with `NOT IMPLEMENTED` all about. 

I will read the rfc when I have some time here.
