### ISSUE TITLE
Provide ways for airgapped node/npm/yarn install

### ISSUE THREAD

**Issue by dimasahmad** [volta-cli/volta#1804] opened 2024-07-18 16:34 UTC
I use volta on my workstation to populate the node and npm install locally, then move them to airgapped machines. Since my company policy now prohibits installing unapproved applications (which volta falls into), I need an alternative way to download the node and npm packages using normal browsers/other tools without administrator privileges.

**Comment by chriskrycho** [comment] 2024-07-22 13:20
Hmm, if you cannot install Volta onto the target machines, then I don’t think Volta *itself* should change to support this. Your best bet is likely to write some scripts that take advantage of [the `volta which` command][which] to know where a given item is for the sake of copying it to the destination.

I am closing this, but feel free to follow up with further questions/discussion!

[which]: https://docs.volta.sh/reference/which

**Closed by chriskrycho** 2024-07-22 13:20 UTC

**Comment by dimasahmad** [comment] 2024-07-22 15:44
Installation should be pretty straight forward. You only need to download the installer for windows, and it definitely can be done for linux.

What I'm struggling with is the node and npm installation method. As I don't have volta on my company laptop anymore, I cannot download the node versions and them move it to the airgapped environment.

If you knew pyenv (in Windows it's pyenv-win), you can just download installers from python's website and put them in a specific folder inside pyenv. They will use that "cached installer" instead of conecting to internet, making airgapped installation more practical.

So what I'm inquiring is, how to add a new node version by placing node installer files so volta will detect the installer? Or how to manually add a new version by extracting node zip archives to where?

**Comment by chriskrycho** [comment] 2024-07-22 22:37
If you *can* put Volta on the target system, and the problem is simply that you cannot have general internet access, that workflow should be reasonably straightforward to support using [hooks](https://docs.volta.sh/advanced/hooks).
