### ISSUE TITLE
error: Could not unpack Node v20.15.0

### ISSUE THREAD

**Issue by dougg0k** [volta-cli/volta#1773] opened 2024-06-21 15:10 UTC
```
error: Could not unpack Node v20.15.0

Please ensure the correct version is specified.
Error details written to /home/user/.volta/log/volta-error-2024-06-21_12_07_14.142.log
```

```
       │ File: /home/user/.volta/log/volta-error-2024-06-21_12_07_14.142.log
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ "/home/user/.volta/bin/volta" "install" "node@lts"
   2   │ Volta v1.1.1
   3   │
   4   │ Could not unpack Node v20.15.0
   5   │
   6   │ Please ensure the correct version is specified.
   7   │
   8   │ Error cause: failed to unpack `/home/user/.volta/tmp/.tmpSWJocN/node-v20.15.0-linux-x64/bin/node`
   9   │
  10   │ Error cause: failed to unpack `/home/user/.volta/tmp/.tmpSWJocN/node-v20.15.0-linux-x64/bin/node`
  11   │
  12   │ Error cause: failed to unpack `node-v20.15.0-linux-x64/bin/node` into `/home/user/.volta/tmp/.tmpSWJocN/node-v20.15.0-linux-x64/bin/node`
  13   │
  14   │ Error cause: Resource temporarily unavailable (os error 11)
```

---

It succeeded the second time, so unsure why. Will leave the issue open in case it can be used to do anything about it.

**Comment by CyntiBinti** [comment] 2024-06-26 15:25
Same issue for me and oddly as well it succeeded when I re-ran `npm i` command 🤔

**Comment by D3X** [comment] 2024-06-27 15:27
I'm on macOS 14.5 and re-running it does not solve the issue. The error message is a bit different, though:

```
"volta" "install" "node"
Volta v1.1.1

Could not unpack Node v20.15.0

Please ensure the correct version is specified.

Error cause: failed to unpack `/Users/.../.volta/tmp/.tmpntJmvM/node-v20.15.0-darwin-arm64/bin/node`

Error cause: failed to unpack `/Users/.../.volta/tmp/.tmpntJmvM/node-v20.15.0-darwin-arm64/bin/node`

Error cause: failed to unpack `node-v20.15.0-darwin-arm64/bin/node` into `/Users/.../.volta/tmp/.tmpntJmvM/node-v20.15.0-darwin-arm64/bin/node`

Error cause: corrupt deflate stream
```

I tried removing the whole `~/.volta` directory and reinstalling everything from scratch, but it didn't help

**Comment by chriskrycho** [comment] 2024-07-08 22:29
I think this *may* be related to #1744 – if any of you folks are up for running a special lots-of-extra-tracing build I just created, see #1784 and follow the instructions under **To Test** there!

**Comment by chriskrycho** [comment] 2024-07-08 22:30
Also, marking this as a duplicate of #1484 and closing it!

**Closed by chriskrycho** 2024-07-08 22:30 UTC
