### ISSUE TITLE
Query the version that can be installed

### ISSUE THREAD

**Issue by tonycody** [volta-cli/volta#1578] opened 2023-11-27 06:11 UTC
It's like nvm

```shell
nvm ls-remote
```

How do I use volta to find out which node versions are available to install?

**Comment by chriskrycho** [comment] 2023-11-27 16:56
Ah, I knew we had this somewhere; #573 is the issue tracking this already. Closing this one as a duplicate of that one. Thanks!

**Closed by chriskrycho** 2023-11-27 16:56 UTC
Labels: duplicate, enhancement, question
