### ISSUE TITLE
windows global command issue

### ISSUE THREAD

**Issue by lifeart** [volta-cli/volta#635] opened 2020-01-05 21:00 UTC
![image](https://user-images.githubusercontent.com/1360552/71786001-91664080-3017-11ea-9f30-b43782fc7369.png)

```
=================================================================================

ENV Summary:

  TIME: Sun Jan 05 2020 23:52:47 GMT+0300 (GMT+03:00)
  TITLE: ember
  ARGV:
  - C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.14.0\6.13.4\node.exe
  - \\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\bin\ember
  - addon
  - ember-click-outside-modifier
  EXEC_PATH: C:\Users\lifeart\AppData\Local\Volta\tools\image\node\12.14.0\6.13.4\node.exe
  TMPDIR: C:\Users\lifeart\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Users\lifeart\AppData\Local\Volta\tools\image\node\12.14.0\6.13.4;C
  - \Users\lifeart\AppData\Local\Volta\tools\image\yarn\1.21.1\bin;C
  - \Python27\;C
  - \Python27\Scripts;C
  - \ProgramData\DockerDesktop\version-bin;C
  - \Program Files\Docker\Docker\Resources\bin;C
  - \Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C
  - \ProgramData\Boxstarter;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C
  - \Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Windows\System32\OpenSSH\;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files\Intel\Intel(R) Management Engine Components\DAL;C
  - \Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
  - \Program Files\Intel\Intel(R) Management Engine Components\IPT;C
  - \ProgramData\chocolatey\bin;C
  - \Program Files\Git\cmd;C
  - \Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files\nodejs\;C
  - \Program Files\AdoptOpenJDK\jdk8u192-b12\bin;C
  - \Program Files\Java\jdk1.8.0_211\bin;C
  - \Android\android-sdk\tools;C
  - \Android\android-sdk\platform-tools;C
  - \Android\android-sdk\tools\bin;C
  - \Program Files\Intel\WiFi\bin\;C
  - \Program Files\Common Files\Intel\WirelessCommon\;C
  - \Users\lifeart\.cargo\bin;C
  - \Users\lifeart\AppData\Local\Microsoft\WindowsApps;C
  - \Users\lifeart\AppData\Local\Programs\Microsoft VS Code\bin;C
  - \Users\lifeart\AppData\Local\GitHubDesktop\bin;C
  - \Users\lifeart\AppData\Local\Microsoft\WindowsApps;C
  - \Users\lifeart\AppData\Roaming\npm;C
  - \flutter\bin;
  PLATFORM: win32 x64
  FREEMEM: 9052762112
  TOTALMEM: 16729128960
  UPTIME: 174760
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz - 2208
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 5
  - nghttp2: 1.39.2
  - node: 12.14.0
  - openssl: 1.1.1d
  - tz: 2019c
  - unicode: 12.1
  - uv: 1.33.1
  - v8: 7.7.299.13-node.16
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: ENOENT
  - codeFrame: [undefined]
  - errorMessage: ENOENT: no such file or directory, scandir '\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\blueprints\app\files/'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: ENOENT: no such file or directory, scandir '\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\blueprints\app\files/'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: ENOENT: no such file or directory, scandir '\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\blueprints\app\files/'
    at Object.readdirSync (fs.js:854:3)
    at _walkSync (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\node_modules\walk-sync\index.js:119:26)
    at walkSync (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\node_modules\walk-sync\index.js:19:12)
    at Class.files (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\lib\models\blueprint.js:241:21)
    at Class.files (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\blueprints\addon\index.js:155:64)
    at Class.install (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\lib\models\blueprint.js:448:43)
    at \\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\lib\tasks\install-blueprint.js:49:24
    at tryCatcher (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\node_modules\rsvp\dist\rsvp.js:498:33)
    at publish (\\?\C:\Users\lifeart\AppData\Local\Volta\tools\image\packages\ember-cli\3.15.1\node_modules\rsvp\dist\rsvp.js:484:9)

=================================================================================

```

**Comment by chriskrycho** [comment] 2020-01-07 22:59
Thanks for reporting this! What version of Volta did you see this with?

**Comment by lifeart** [comment] 2020-01-08 15:52
volta -v `0.6.8`

Can reproduce only in builtin `cmd`, git bash works `ok`

**Comment by charlespierce** [comment] 2020-01-08 17:28
@lifeart This looks similar to #586, ultimately caused by a conflict between Volta using extended-length paths and Node scripts using concatenation to create paths, instead of `path.join`. We'll do some testing to see if we can avoid using the extended-length paths, which hopefully should resolve these types of issues.

@rwjblue At the same time, could you point me to where in the `ember-cli` codebase the blueprint work is, perhaps it's something that could be easily fixed on that side as well.

**Closed** 2020-01-09 23:58 UTC
Labels: bug
