### ISSUE TITLE
Unable to pin tooling

### ISSUE THREAD

**Issue by NullVoxPopuli** [volta-cli/volta#1125] opened 2021-12-24 20:32 UTC
```
❯ volta pin pnpm
error: Only node and yarn can be pinned in a project

Use `npm install` or `yarn add` to select a version of pnpm for this project.
```

doesn't make sense to me that only node and yarn would be pinnable :thinking:

**Comment by chriskrycho** [comment] 2021-12-24 21:06
Duplicate of #737. We need to implement specific support for package managers: they all work in subtly and importantly different ways.

**Closed** 2021-12-24 21:06 UTC
