### ISSUE TITLE
Volta doesn't (willingly) update globally installed npm packages

### ISSUE THREAD

**Issue by constb** [volta-cli/volta#929] opened 2021-01-31 11:25 UTC
So, here's the case. I have pnpm package installed using volta. I run pnpm, it detects that there's new version available:

```
   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 5.15.1 → 5.16.0                 │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v5.16.0   │
   │                  Run pnpm i -g pnpm to update!                   │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯
```

I'm trying to find some way to install updated version automatically:

```
$ volta install pnpm@latest
success: installed pnpm@5.15.2 with executables: pnpm, pnpx
$ volta fetch pnpm
error: Fetching packages without installing them is not supported.

Use `volta install pnpm` to update the default version.
$ volta install pnpm
success: installed pnpm@5.15.2 with executables: pnpm, pnpx
```

For some reason volta is willing to install 5.15.2 as a replacement for 5.15.1. But it will only update to 5.16.0 if this version is explicitly specified:

```
$ volta install pnpm@5.16.0
success: installed pnpm@5.16.0 with executables: pnpm, pnpx
```

How do I force updating to the actual latest version without explicitly specifying its version number?

**Comment by charlespierce** [comment] 2021-01-31 17:34
Hi @constb! I can't reproduce this currently: Running `volta install pnpm` shows `success: installed pnpm@5.16.0 with executables: pnpm, pnpx`. Under the hood, `volta install` pulls the version data from the npm registry, so perhaps it was the case that when you ran into this issue, the npm registry wasn't updated so that `latest` pointed at `5.16.0`? Or if you use a private registry that mirrors the global registry (via `~/.npmrc` or similar), perhaps that private registry doesn't yet reflect the changes to the tags?

If this is still reproducible on your side and none of the above issues with the npm registry apply, could you provide some more info:

- Which version of Volta are you running?
- What is the output of `npm view pnpm`?

**Comment by constb** [comment] 2021-02-01 04:54
> I can't reproduce this currently: Running `volta install pnpm` shows `success: installed pnpm@5.16.0 with executables: pnpm, pnpx`.

I'm guessing you didn't have pnpm installed beforehand? Clean `volta install` always pulls in latest version, that behaviour is correct. The issue is updating it later. I had 5.15.1 installed (with volta) before, and then it updates to 5.15.2 but not to 5.16.0.

```
$ volta --version
1.0.1
```

installed on MacOS Catalina from homebrew

```
$ npm view pnpm

pnpm@5.16.0 | MIT | deps: none | versions: 641
Fast, disk space efficient package manager
https://pnpm.js.org

keywords: dependency manager, install, installer, uninstall, remove, link, prune, shrinkwrap, lockfile, fast, rapid, efficient, package.json, packages, dependencies, symlinks, hardlinks, modules, npm, package manager, monorepo, multi-package, workspace

bin: pnpm, pnpx

dist
.tarball: https://registry.npmjs.org/pnpm/-/pnpm-5.16.0.tgz
.shasum: 0a353b015c3f9afd93657aff649adb5e385274de
.integrity: sha512-f7bNVvYGK24eiZ5gYX4wKOSohg6kIybEhrprHqUtFsP3TfttGSLqid1OTzLvVzwVp58QBj9ifOVwRQ+RiSmE0A==
.unpackedSize: 11.0 MB

maintainers:
- zkochan <z@kochan.io>

dist-tags:
dev: 0.0.0-20201060511  latest-1: 1.43.1        latest-2: 2.25.7        latest-3: 3.8.1         latest-4: 4.14.4        latest: 5.16.0          next: 5.16.0            rc: 5.16.0

published 6 days ago by zkochan <z@kochan.io>
```

I'm don't have a private registry, but I do have several settings in .npmrc, that, I'm thinking, may affect that:

```
$ cat ~/.npmrc
save-exact=true
prefer-offline=true
send-metrics=true
update-notifier=false
```

**Comment by charlespierce** [comment] 2021-02-01 20:50
Ah, that last bit is likely the cause: the `prefer-offline` settings tells npm to use its local cache wherever possible. My guess is that your local copy of the npm registry metadata for `pnpm` thinks (or thought) that `5.15.2` is the `latest` so it was using that (`volta install` uses `npm install` under the hood).

**Comment by constb** [comment] 2021-02-02 06:21
@charlespierce that's exactly it! thank you!

I confirmed this on another package. With `prefer-offline=true`:

```
$ volta install npm-check-updates@latest
success: installed npm-check-updates@9.0.3 with executables: npm-check-updates, ncu
```

After commenting it out:

```
$ volta install npm-check-updates@latest
success: installed npm-check-updates@11.1.1 with executables: npm-check-updates, ncu
```

Do I close the issue, or is there something that should be done about that in volta? Like printing some warning message or something?

**Comment by charlespierce** [comment] 2021-02-02 06:24
Thanks for confirming! I don't know that there's much we can do within Volta itself, at least without completely recreating the `npm` configuration logic, so I'll close the issue.

**Closed by charlespierce** 2021-02-02 06:24 UTC

**Comment by ljharb** [comment] 2021-02-02 14:26
Volta could set the env var `NPM_CONFIG_PREFER_OFFLINE=false` before invoking npm, but that seems like it'd be more confusing than the current behavior for those that know they've configured prefer-offline to true.
