### ISSUE TITLE
Installing packages with volta on Ubuntu 18.04.2 LTS (on Linode) fails with EACCES

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#485] opened 2019-06-22 15:05 UTC
[This may be a machine-specific issue, so I'm still digging further.]

Running `volta install ghost-cli` fails with an `EACCES` error with the following verbose output (and I see the same with other packages, e.g. `ember-cli`):

```sh
$ volta install --verbose ghost-cli@latest
[verbose] No custom hooks found
[verbose] Found ghost-cli latest version (1.11.0) from https://registry.npmjs.org/ghost-cli
[verbose] Loading ghost-cli@1.11.0 from cached archive at /home/chris/.volta/tools/inventory/packages/ghost-cli-1.11.0.tgz
[verbose] Unpacking ghost-cli@1.11.0 in /home/chris/.volta/tmp/.tmp03sEEk
[verbose] Installing ghost-cli@1.11.0 in /home/chris/.volta/tools/image/packages/ghost-cli/1.11.0
[verbose] Found 'engines.node' specification for ghost-cli@1.11.0: ^8.9.0 || ^10.13.0
[verbose] Found node@10.16.0 matching requirement '>= 8.9.0, < 9.0.0 || >= 10.13.0, < 11.0.0' from https://nodejs.org/dist/index.json
[verbose] Loading node@10.16.0 from cached archive at /home/chris/.volta/tools/inventory/node/node-v10.16.0-linux-x64.tar.gz
[verbose] node@10.16.0 has already been fetched, skipping install
[verbose] Installing dependencies with command: "npm" "install" "--only=production" "--loglevel=warn" "--no-update-notifier" "--no-audit" "--color=always"
[verbose] [install stderr]
Unhandled rejection Error: EACCES: permission denied, open '/home/chris/.npm/_cacache/index-v5/f1/0d/c6029d51f93afd01a0113d7d479df0817dcf4fb9386094683c5ab033d76e'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2019-06-22T15_00_36_268Z-debug.log

[verbose] [install stdout]

error: Could not install package dependencies.

Please ensure you have correct permissions to the Volta directory.
```

Note that the installation appears to be attempting to access `~/.npm`, *not* just its own installation context. I will do a bit further digging and see if I can identify why it's doing that.

I also note that the error we report here is not quite correct. It's reasonable to infer that for well-behaved packages, their installation will *not* go poking around the rest of the system and therefore hit `EACCES` issues outside Volta. However, in cases where they *do*, if we *can* surface the actual location that was missed, that'd be an improvement.

**Comment by charlespierce** [comment] 2019-06-22 15:28
For the last piece, I don’t know that we _can_ get the actual location where the problem is, since all we get from npm is a failure error code. Short of doing some parsing of the stderr output, which seems highly error-prone, they don’t really tell us what went wrong.

We could, however, change the CTA to not make the assumption that it’s a permissions issue and instead come up with something more general.

As for the exact error, it looks like it’s npm’s internal local cache that is having issues. I’m curious if you see the error running `npm install ghost-cli`

**Comment by chriskrycho** [comment] 2019-06-22 15:32
My guess was the same about the actual permissions issue. We might suggest running with `--verbose` in that error message (not something I'd suggest adding in general, but here it's likely to actually surface the issue?).

I'm also finding other issues with this particular system in a variety of ways after upgrading it to Ubuntu 18.04 a few weeks ago, so it's *possible* that's at root. Lending further credence to it being a system config issue: that I see the exact same error for `ember-cli` as for `ghost-cli`, and we know `ember-cli` installs just fine on other Linux systems with Volta.

**Comment by charlespierce** [comment] 2021-02-12 19:29
Closing as there hasn't been any update and it looks like this was a localized issue. Feel free to re-open if it crops up again!

**Closed by charlespierce** 2021-02-12 19:29 UTC
Labels: bug, error messages
