### ISSUE TITLE
Volta error: Could not unpack Node

### ISSUE THREAD

**Issue by happy-turtle** [volta-cli/volta#1546] opened 2023-08-29 06:50 UTC
Hello 👋 We are running Volta in a Github action runner and are experiencing frequent failures. This is getting so frequent that it requires retries every time and is not very much production ready. After a few retries it eventually runs fine though. Do you have any hints what the problem might be? The Volta installation runs fine, but it then fails on unpacking Node.

```
Run npm ci
  npm ci
  shell: /usr/bin/bash -e {0}
  env:
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.1.1/x64
Volta error: Could not unpack Node v18.16.1

Please ensure the correct version is specified.
Volta error: Error cause: failed to unpack `/opt/hostedtoolcache/volta/1.1.1/x64/tmp/.tmpsOnC5r/node-v18.16.1-linux-x64/bin/node`

Error cause: failed to unpack `/opt/hostedtoolcache/volta/1.1.1/x64/tmp/.tmpsOnC5r/node-v18.16.1-linux-x64/bin/node`

Error cause: failed to unpack `node-v18.16.1-linux-x64/bin/node` into `/opt/hostedtoolcache/volta/1.1.1/x64/tmp/.tmpsOnC5r/node-v18.16.1-linux-x64/bin/node`

Error cause: Resource temporarily unavailable (os error 11)
Error: Process completed with exit code 126.
```
Edit: This was partially mentioned [here](https://github.com/volta-cli/action/issues/77#issuecomment-1540095157) already. But it looks more like an issue directly related to Volta.

**Comment by DerJacques** [comment] 2023-08-29 14:34
We're running into the same issues. Two different machines on different networks, specifying different versions of node.
This has worked fine for us previously.

The [node status page](https://status.nodejs.org/) doesn't show any issues at the time of this message.

**Comment by felipecrs** [comment] 2023-08-31 22:01
Duplicate of https://github.com/volta-cli/volta/issues/1523.

**Comment by chriskrycho** [comment] 2023-09-23 02:37
Closing this as a duplicate of #1523. We *are* thinking about this problem, but none of us has yet had time to tackle it. See [my latest comment there](https://github.com/volta-cli/volta/issues/1523#issuecomment-1732187410) for our current best guesses as to what's going on!

**Closed by chriskrycho** 2023-09-23 02:37 UTC
