### ISSUE TITLE
nested volta invocations

### ISSUE THREAD

**Issue by chriseppstein** [volta-cli/volta#702] opened 2020-04-01 20:34 UTC
When code in a javascript project that uses volta tries to execute a volta-controlled binary in another javascript project that also uses volta, the behavior is not what one would expect. The `PATH` environment variable will be set to the binary versions that the first-invoked project uses.

Here's some typescript code that I wrote to work around this issue:

```ts
export function restoreVoltaEnvironment() {
  let voltaHome = process.env["VOLTA_HOME"];
  if (!voltaHome) return;
  let paths = process.env["PATH"]!.split(path.delimiter);
  while (/\.volta/.test(paths[0])) {
    paths.shift;
  }
  paths.unshift(`${voltaHome}/bin`)
  process.env["PATH"] = paths.join(path.delimiter);
}
```

I'm curious whether this sort of workaround is expected for these situations? If so, does the code I've written here look reasonable?

**Comment by toshok** [comment] 2020-04-02 06:15
We've run into this with a `volta install`ed CLI (`gsts`) that re-spawns itself.  Unfortunately in this case we really don't have any recourse.

**Comment by charlespierce** [comment] 2020-04-02 06:30
@chriseppstein Can you talk more about the use-case of one JS project calling a tool that is managed by Volta in another project directory? Specifically how you would expect it to work, and how it currently works in a system without Volta?

We have issue #492 as a potential solution to a whole class of issues relating to global tools interacting with each other, which may be a solution, though in the initial brainstorm it would still result in only a single version of Node.

@toshok That's an interesting case, can you expand on it? Does it fail, or is it that it uses an unexpected version of Node?

**Comment by chriseppstein** [comment] 2020-04-02 15:34
@charlespierce In my situation, the tool isn't being distributed as a published executable. You checkout the code, `yarn install` and the `yarn run` various package scripts. The tool is used to help build and test other javascript projects so it executes `yarn install` and `yarn run` as spawned processes from within those other checked out package directories. Because it's a separate process, I expect the node and yarn versions of those other projects to match their specific volta configurations.

**Comment by charlespierce** [comment] 2020-04-02 17:15
@chriseppstein Short term, since you control the code that's launching these other tools, I think that your workaround makes sense to "reset" the environment so Volta starts fresh. Longer term something like #492 may also provide the behavior you need. However, there are a lot of unanswered questions (several of which you note) about what the most common expected behavior will be, which is why we have that issue marked as "Needs RFC". We'll need to hash out the possible flows and determine what makes the most sense for the majority of use-cases.

**Comment by charlespierce** [comment] 2020-04-02 17:19
@toshok I see the code in `gsts` that respawns itself, and why it doesn't work currently with Volta. I think that will be fixed by #492 regardless of the decisions about environment, but until that lands it doesn't look like it will work cleanly. We could potentially open an issue in `gsts` to have it be more agnostic about the environment when it respawns itself, not relying on the assumption that `gsts` is on the PATH.

**Comment by toshok** [comment] 2020-04-02 17:19
re: our problem, it fails to spawn with ENOENT:

```
$ which gsts
/Users/toshok/.volta/bin/gsts
$ gsts
User is not authenticated, spawning headful instance
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn gsts ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn gsts',
  path: 'gsts',
  spawnargs: [
    '--headful',
    '--awsProfile=sts',
    '--awsSharedCredentialsFile=/Users/toshok/.aws/credentials',
...
  ]
}
```

`PATH`s seem to point out the proximal "why" (same as original issue):

```
$ echo $PATH
/Users/toshok/.volta/bin:/Users/toshok/.goenv/shims:...

$ node -e 'console.log(process.env.PATH)'
/Users/toshok/.volta/tools/image/node/12.16.1/6.13.4/bin:/Users/toshok/.volta/tools/image/yarn/1.22.4/bin:/Users/toshok/.goenv/shims:...
```

**Comment by charlespierce** [comment] 2020-04-02 17:57
@toshok It's a super small fix, so I just submitted a PR (and associated issue) to `gsts`: https://github.com/ruimarinho/gsts/pull/6

**Comment by charlespierce** [comment] 2020-04-02 19:14
@toshok That change landed and was published, so `gsts@2.1.4` should now work with Volta.

@chriseppstein Closing in favor of #492 as the overall approach to fixing tools interacting with other tools.

**Closed by charlespierce** 2020-04-02 19:14 UTC

**Comment by nhhockeyplayer** [comment] 2022-07-09 22:20
why is volta interfering with github actions workflow and NxCloud?

Error: spawn volta ENOENT

who is releasing bad stuff into the public domain ?

**Comment by nhhockeyplayer** [comment] 2022-07-09 22:24
can the owner if this repo consider what developers are encountering right now on NxCloud and github actions?

no one wants to begin profiling bad committers to the public domain

thanks for your attention to this

this log failure appears to have your repo name on it

```
${GITHUB_WORKSPACE//\\//}/.github/workflows/run-commands-in-parallel.sh '["NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- volta install node@16","NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx workspace-lint","NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx format:write","NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx-cloud record -- npx nx format:check","npx nx affected --target=lint --parallel=3","npx nx affected --target=test --parallel=3 --ci","npx nx affected --target=build --parallel=3"]'
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: [3](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:3)
    NX_BRANCH: main
    NX_CLOUD_ACCESS_TOKEN: 
    NX_CLOUD_AUTH_TOKEN: 
    NX_BASE: a[4](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:4)[5](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:5)deaa017[6](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:6)c[7](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:7)36ed235c427[8](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:8)645b[9](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:9)5f4d31b498
    NX_HEAD: fdd2ceb52e38e073fa19b21230ab77176d[11](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:11)135c
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.0.8/x64
node:events:505
      throw er; // Unhandled 'error' event
      ^
Error: spawn volta ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:[12](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:12))
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn volta',
  path: 'volta',
  spawnargs: [ 'install', 'node@16' ]
}
 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: a45deaa0176c736ed235c4278645b95f4d31b498
 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: fdd2ceb52e38e073fa19b21230ab77176d11[13](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:14)5c
 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: a45deaa0[17](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:18)6c736ed235c4278645b95f4d31b498
 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: fdd2ceb52e38e073fa[19](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:20)b[21](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:22)[23](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:24)0ab77176d11135c
 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: a45deaa0176c736ed235c4[27](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:28)8645b95f4d31b498
 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: fdd2ceb52e38e073fa19b212[30](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:31)ab77176d111[35](https://github.com/nhhockeyplayer/meanstacknh/runs/7266585159?check_suite_focus=true#step:21:36)c
 >  NX   Starting distributed command execution
 >  NX   Starting distributed command execution
 >  NX   Waiting...
 >  NX   Waiting...
 >  NX   Starting distributed command execution
 >  NX   Waiting...
 >  NX   Nx Cloud: Successfully recorded command output
   You can view or share your output by visiting https://nx.app/runs/BzliwX7Yvcw
README.NxCloud-Ci-CD.nm.github.md
README.NxCloud-Ci-CD.nm.github.md
libs/admin/root/feature-shell/package.json
libs/admin/root/feature-shell/package.json
libs/shared/feature/auth/package.json
libs/shared/material/package.json
libs/shared/root/data-access/package.json
libs/shared/root/service/package.json
nx.json
nx.json
Error: Process completed with exit code 1.
```

**Comment by charlespierce** [comment] 2022-07-10 00:32
@nhhockeyplayer Can you clarify your question? Where is that error log from?

Volta doesn't have any direct association with NX or GitHub Actions (other than that we publish our own GitHub Action that you can use in your own workflows). Volta itself is a tool for managing Node versions. The above error message seems to be from a command that is attempting to run a Volta command without having Volta installed.

**Comment by nhhockeyplayer** [comment] 2022-07-10 12:03
Hi Thanks...

github actions permits users to publish their packages to their registry... just like npm does

and so there is an eFrastructure platform in place operating YML files in order to setup, build, bundle and publish kinda like docker does to clouds

these YML files run out to the package world and pull in things to complete the operations confiured in YML files beneath any projects <ROOT-PROJECT-DIR>/github/workflows/ci.yml
 
for continuous integration

yours is landing in my work flow and the failure is happening with your package

does this help context?

thanks for fast reply I appreciate it

**Comment by nhhockeyplayer** [comment] 2022-07-10 12:09
I dont know who is setting up VOLTA_HOME

I will search a few repo's and try to find out

**Comment by nhhockeyplayer** [comment] 2022-07-10 14:04
> @nhhockeyplayer Can you clarify your question? Where is that error log from?
> 
> Volta doesn't have any direct association with NX or GitHub Actions (other than that we publish our own GitHub Action that you can use in your own workflows). Volta itself is a tool for managing Node versions. The above error message seems to be from a command that is attempting to run a Volta command without having Volta installed.

okay so it appears some internal systemic platform yml file either github actions or nxcloud is operating volta for some maybe fallback thing maybe and has no actual install

do you have an install sequence you can share and I will add it to my ci.yml?

thanks
