### ISSUE TITLE
Source the pinned Node version from .node-version as a fallback

### ISSUE THREAD

**Issue by hitsthings** [volta-cli/volta#1553] opened 2023-09-20 00:34 UTC
I thought I saw a request for this somewhere, but can't find it now so I'm creating one, at least to understand your thoughts on whether it's something you'd welcome or not.

I use Volta, but others on the team use other managers. I'd like if Volta supported the `.node-version` file for pinning a Node version in a project. Would be one fewer spot to keep in sync  when bumping the version. There are [a bunch of other projects](https://stackoverflow.com/a/62978089/37685) that support that file, so it seems like a good one to standardize on.

Cheers!

**Comment by chriskrycho** [comment] 2023-09-23 02:21
Hi @hitsthings, thanks for opening this. The previous discussion is at #983, so I'll close this as a duplicate of that! The path forward there is relatively straightforward, but needs a little bit of design and implementation, which—alas!—none of the maintainers have had time to take on.

**Closed by chriskrycho** 2023-09-23 02:21 UTC

**Comment by hitsthings** [comment] 2023-09-23 03:15
Thanks! Not sure why I couldn't find that in search. Subscribed.
