### ISSUE TITLE
Cannot install Volta in Docker container running on Mac M1

### ISSUE THREAD

**Issue by zfields** [volta-cli/volta#1181] opened 2022-03-17 19:55 UTC
```none
> [3/4] RUN curl https://get.volta.sh/ | bash:                                  
#6 0.185   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#6 0.185                                  Dload  Upload   Total   Spent    Left  Speed
100 12319  100 12319    0     0   9557      0  0:00:01  0:00:01 --:--:--  9557  
#6 1.478 Error: Sorry! Volta currently only provides pre-built binaries for x86_64 architectures.
#6 1.478 
------
executor failed running [/bin/sh -c curl https://get.volta.sh/ | bash]: exit code: 1
[3023 ms] Command failed: docker build -f /Users/roblauer/Documents/GitHub/wireless.dev/wireless-dev-site/Dockerfile -t vsc-wireless.dev-6836c51d289a895376311366280cdf1c /Users/roblauer/Documents/GitHub/wireless.dev/wireless-dev-site
[3023 ms] Exit code 1
```

**Comment by charlespierce** [comment] 2022-03-23 23:42
Hi @zfields, thanks for reporting! I'm guessing this is a duplicate of #1049, or at least has the same root cause: We don't currently provide a pre-built binary for ARM Linux environments. I'm quite far from an expert in Docker, but my guess is that since M1 is an ARM architecture, the docker image is similarly using the same underlying architecture for the linux distro.

**Closed by charlespierce** 2022-03-23 23:42 UTC
