### ISSUE TITLE
Confusing output of `volta ls`: Packages and associated Node version always `default`

### ISSUE THREAD

**Issue by svenjacobs** [volta-cli/volta#1226] opened 2022-05-06 06:03 UTC
According to the Volta [guide](https://docs.volta.sh/guide/understanding#managing-your-toolchain)

> When you install a package to your toolchain, Volta takes your current default Node version and pins the tool to that engine

Either I don't understand the output of `volta ls` or I have a bug here. With a fresh installation of Volta 1.0.7, I first installed Node 18.1.0 and a few packages via `volta install`. This is the output:

```
~ volta ls
⚡️ Currently active tools:

    Node: v18.1.0 (default)
    Tool binaries available:
        vue (default)
        firebase (default)
        npm-check-updates, ncu (default)
        pnpm, pnpx (default)
```

Looks fine so far. Now I installed Node 16.15.0. Volta made it the default version. The output is now:

```
~ volta ls
⚡️ Currently active tools:

    Node: v16.15.0 (default)
    Tool binaries available:
        vue (default)
        firebase (default)
        npm-check-updates, ncu (default)
        pnpm, pnpx (default)
```

I assumed the binaries should now display something like `vue (18.1.0)` since this is the pinned Node version of that binary. Do I misunderstand this feature or is this a bug?

OS: macOS 12.3.1
Shell: zsh 5.8.1

**Comment by svenjacobs** [comment] 2022-05-26 13:36
Could someone please explain this to me since I'm still confused. Many thanks!

**Comment by charlespierce** [comment] 2022-06-09 14:36
Hi @svenjacobs, sorry for the delay, I've been busy with other projects! I believe this is a bug / oversight in the `volta list` output relating to determining the version of the tool binaries available. The `(default)` _should_ be the version of the tool itself, not the Node, and we should separately be showing the associated Node version. I think this is a duplicate of #711, which details some additional pieces of information that are missing from the various list outputs.

**Closed by charlespierce** 2022-06-09 14:36 UTC

**Comment by svenjacobs** [comment] 2023-06-05 06:28
With `volta list all` I can get the desired information 🎉
