### ISSUE TITLE
uninstall failed

### ISSUE THREAD

**Issue by lazy-coder97** [volta-cli/volta#1760] opened 2024-05-23 03:11 UTC
<img width="462" alt="image" src="https://github.com/volta-cli/volta/assets/134416734/e50ec580-ebfa-4688-a23c-72e3dba85633">
Why would it say the package is not found?

**Comment by tang-nn** [comment] 2024-07-07 05:41
![image](https://github.com/volta-cli/volta/assets/98725149/4749ed83-e05f-4f80-89a4-e89d09de606e)

**Comment by chriskrycho** [comment] 2024-07-09 19:35
Yarn is not a package, but rather a package manager, and we do not currently support uninstalling package managers – see #330 and especially #327 for further details. Closing this as a duplicate of #327 specifically! (That said, I think we could maybe help here with some better messaging!)

**Closed by chriskrycho** 2024-07-09 19:35 UTC
