### ISSUE TITLE
Cannot use in Ubuntu 22.04

### ISSUE THREAD

**Issue by felipecrs** [volta-cli/volta#1180] opened 2022-03-09 04:09 UTC
After installing it, I receive the following error when trying to run:

```console
$ volta
volta: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Out of curiosity:

```console
$ openssl version
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
```

**Comment by felipecrs** [comment] 2022-03-09 04:13
This solves the issue:

```console
sudo apt update && sudo apt install libssl1.1 -y
```

But I suppose this was not supposed to be needed. Ideally the Volta binary should contain all it needs?

**Comment by charlespierce** [comment] 2022-03-09 18:44
My guess is that this is a duplicate of #1150: Currently we build against OpenSSL 1.0 and OpenSSL 1.1. We have an open RFC https://github.com/volta-cli/rfcs/pull/47 for switching to `Rustls`, which would statically link and avoid OpenSSL compatibility issues (which are a _huge_ pain). There's also some in-progress work towards that end, which has hit some snags with our environment / backwards compatibility needs.

Good to know that this is the case for the next major Ubuntu release, I think that bumps the priority up!

**Closed** 2022-03-09 18:58 UTC

**Comment by felipecrs** [comment] 2022-04-20 15:42
Ubuntu 22.04 LTS will be released tomorrow, by the way, and indeed Volta is unusable there right now.

**Comment by tr-jason** [comment] 2022-04-22 01:00
> Ubuntu 22.04 LTS will be released tomorrow, by the way, and indeed Volta is unusable there right now.

Confirmed
